encoding: UTF-8
# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["tables","no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#pygments:         true
highlighter: pygments

# Permalinks
permalink:        pretty

# Setup
title:            '@yeradis'
tagline:          'Computer Science, Software, Development, Programming, Python, Java, MongoDB,Flask,RabbitMQ, Software Engineering'
url:              http://yeradis.github.io
shorturl:         yeradis.github.io
baseurl: 	  "/blog"
author:
  name:           'Yeradis P. Barbosa Marrero'
  url:            https://twitter.com/yeradis
  twitter:		  yeradis
  facebook:		  yeradis
  github:		  yeradis
  linkedin:		  yeradis

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/yeradis/yeradis.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Tags: '/tags'
  Feed: '/atom.xml'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
